name: Entur/Meta/CloudAuth
description: Authenticate with cloud provider
inputs:
  environment:
    description: "GitHub environment to use Google Cloud: (dev, tst, prd) or Azure: (az-dev, az-test, az-prod)"
    required: true
  cloud_provider:
    description: "Which cloud service provider to use - Google Cloud: 'gcp' or Azure: 'az'"
    default: "gcp"
  workload_identity_provider:
    description: "Workload identity provider to use for authentication"
  service_account:
    description: "Service account to use for authentication"
  azure_client_id:
    description: "Azure client ID"
  azure_tenant_id:
    description: "Azure tenant ID"
  azure_subscription_id:
    description: "Azure subscription ID"
runs:
  using: "composite"
  steps:
    - id: verify-cloud-provider
      if: inputs.cloud_provider != 'gcp' && inputs.cloud_provider != 'az'
      shell: bash
      env:
        GHA_CLOUD_AUTH_CLOUD_PROVIDER: ${{ inputs.cloud_provider }}
      run: |
        echo "Invalid cloud provider input: ${GHA_CLOUD_AUTH_CLOUD_PROVIDER}"
        echo "Valid options are: 'gcp' or 'az'"
        exit 1
    - id: login-gcp
      name: Authenticate with Google Cloud
      if: inputs.cloud_provider == 'gcp'
      uses: google-github-actions/auth@v2.1.2
      with:
        workload_identity_provider: ${{ inputs.workload_identity_provider }}
        service_account: ${{ inputs.service_account }}
    - id: login-azure
      name: Authenticate with Azure
      if: inputs.cloud_provider == 'az'
      uses: Azure/login@v2
      with:
        client-id: ${{ inputs.azure_client_id }}
        tenant-id: ${{ inputs.azure_tenant_id }}
        subscription-id: ${{ inputs.azure_subscription_id }}
