name: Entur/Meta/CloudAuth
inputs:
  environment:
    description: "The target environment"
    required: true
    type: string
  cloud_provider:
    description: "Which repository to use. GCP/Azure"
    type: string
    default: "GCP"
  token_format:
    description: |-
      Output format for the generated authentication token. For OAuth 2.0 access
      tokens, specify "access_token". For OIDC tokens, specify "id_token". To
      skip token generation, leave this value empty.
    default: ""
    required: false
runs:
  using: "composite"
  steps:
    - id: set-env
      shell: bash
      run: |
        echo "GHA_CLOUD_AUTH_CLOUD_PROVIDER=${{ inputs.cloud_provider }}" >> $GITHUB_ENV
        echo "GHA_CLOUD_AUTH_TOKEN_FORMAT=${{ inputs.token_format }}" >> $GITHUB_ENV
    - id: verify-cloud-provider
      if: env.GHA_CLOUD_AUTH_CLOUD_PROVIDER != 'GCP' && env.GHA_CLOUD_AUTH_CLOUD_PROVIDER != 'Azure'
      shell: bash
      run: |
        echo "cloud_provider can only be GCP or Azure"
        exit 1
    - id: login-gcp
      if: env.GHA_CLOUD_AUTH_CLOUD_PROVIDER == 'GCP'
      uses: google-github-actions/auth@v2.1.2
      with:
        workload_identity_provider: ${{ vars.WORKLOAD_IDENTITY_PROVIDER }}
        service_account: ${{ vars.SERVICE_ACCOUNT }}
        token_format: ${{ env.GHA_CLOUD_AUTH_TOKEN_FORMAT }}
    - id: login-azure
      if: env.GHA_CLOUD_AUTH_CLOUD_PROVIDER == 'Azure'
      uses: Azure/login@v2
      with:
        client-id: ${{ vars.AZURE_CLIENT_ID }}
        tenant-id: ${{ vars.AZURE_TENANT_ID }}
        subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}
