name: Entur/Meta/Doc

on:
  workflow_call:
    inputs:
      workflow_file:
        description: Path to the workflow file
        type: string
      readme_file:
        description: Path to the output file
        type: string
      timeout_minutes:
        description: "Job timeout in minutes"
        type: number
        default: 5

jobs:
  update-doc:
    runs-on: ubuntu-latest
    timeout-minutes: ${{ inputs.timeout_minutes }}
    permissions:
      contents: write
    steps:
      - id: set-env
        shell: bash
        run: |
          echo "GHA_META_WORKFLOW_FILE=${{ inputs.workflow_file }}" >> $GITHUB_ENV
          echo "GHA_META_README_FILE=${{ inputs.readme_file }}" >> $GITHUB_ENV
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - uses: tj-actions/auto-doc@v3
        with:
          filename: ${{ env.GHA_META_WORKFLOW_FILE}}
          reusable: true
          output: ${{ env.GHA_META_README_FILE }}
          use_code_blocks: true
      - uses: tj-actions/verify-changed-files@v20
        id: verify-changed-files
        with:
          files: |
            ${{ env.GHA_META_README_FILE }}
      - uses: EndBug/add-and-commit@v9
        if: steps.verify-changed-files.outputs.files_changed == 'true'
        with:
          message: "docs: Update workflow documentation"
          add: ${{ env.GHA_META_README_FILE }}
